services:
  traq-ing:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '4173:4173'
    env_file:
      - ./apps/server/.env
    volumes:
      - ./traq.db:/app/traq.db
