services:
  traq-ing-client:
    container_name: traq-ing-client
    build:
      context: .
      dockerfile: client.Dockerfile
    restart: always
    networks:
      - traq-ing-network
    ports:
      - '5002:80'
    develop:
      watch:
        - path: ./Caddyfile
          action: rebuild
    environment:
      - SERVER_ORIGIN=traq-ing-server:8080
  traq-ing-server:
    container_name: traq-ing-server
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: always
    ports:
      - '5001:8080'
    networks:
      - traq-ing-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TRAQ_AUTH_CLIENT_ID=${TRAQ_AUTH_CLIENT_ID}
      - TRAQ_TOKEN=${TRAQ_TOKEN}
      - DATABASE_URL=postgressql://user:password@host.docker.internal:5555/traq_ing

networks:
  traq-ing-network:
