name: Release client

on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - '**'

env:
  IMAGE_NAME: traq-ing-client

jobs:
  # GitHubリリース機能で自動リリース
  make-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build:client
        env:
          NODE_ENV: production

      - name: Archive dist/
        run: tar -zcvf ./dist.tar.gz ./dist

      - name: Create Release and upload dist.tar.gz
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          files: dist.tar.gz

  # ghcrにビルド済みイメージをアップロード
  image:
    name: Build Docker Image
    needs:
      - make-dist
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo IMAGE_TAG=$(echo ${GITHUB_REF:11}) >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cp-20
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/cp-20/${{ env.IMAGE_NAME }}:latest
            ghcr.io/cp-20/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=ghcr.io/cp-20/${{ env.IMAGE_NAME }}:buildcache
